services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    mem_limit: 700m
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      retries: 10
      timeout: 10s
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service



  configserver:
    image: "jaypande13/config-server:v0.0.1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
#      test: [ "CMD", "curl", "-f", "<http://localhost:8071/actuator/health" ]
      # - This config is used in the video. explanation below.
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    image: "jaypande13/accounts:v0.0.1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: "jaypande13/loans:v0.0.1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  cards:
    image: "jaypande13/cards:v0.0.1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


networks:
  gringotts:
    driver: bridge
